src/featurerequest/urls.py
from django.conf.urls import url
from . import views

app_name = 'featurerequest'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userlogin/$', views.userlogin, name='userlogin'),
    url(r'^userlogout/$', views.userlogout, name='userlogout'),
    url(r'^add/$', views.add_features, name='add_features'),
    url(r'^page/(?P<page>\d+)/$', views.index, name='index-withpage'),
]

src/serviceitnow/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^features/', include('featurerequest.urls', namespace='featurerequest')),
    url(r'^', include('featurerequest.urls'))
]

src/featurerequest/models.py
from django.db import models
from django.db.models import Max, F
from django.core.validators import MinValueValidator


class Clients(models.Model):
    STATUS_CHOICES = (
        ('A', 'Active'),
        ('I', 'Inactive'),
    )
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    startdate = models.DateTimeField(auto_now_add=True)
    enddate = models.DateField()
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)

    class Meta:
        verbose_name_plural = "clients"

    def __str__(self):
        return self.name


class ProductArea(models.Model):
    STATUS_CHOICES = (
        ('A', 'Active'),
        ('I', 'Inactive'),
    )
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1000)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)

    def __str__(self):
        return self.name


class Features(models.Model):
    STATUS_CHOICES = (
        ('A', 'Active'),
        ('I', 'Inactive'),
        ('D', 'Done'),
        ('C', 'Cancelled'),
    )

    PRIORITY_CHOICES = tuple((i, i) for i in range(0, 16))

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=8000)
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    priority = models.IntegerField(default=0, validators=[MinValueValidator(0)])  # 0 means priority is not set
    start_date = models.DateTimeField(auto_now_add=True)
    target_date = models.DateField()
    product_area = models.ForeignKey(ProductArea,  null=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name_plural = "features"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        1. Overriding save method to address priority reordering.
        2. Only Feature request that have status=A will be priorities.
        3. Priority 0 means the item is not priorities yet. If an item has status=A and priority=0
           then it will not be reordered automatically.
        4. Priority will be always sequential i. e. If priority 1,2,3 is already assigned and new item is added with
           priority 5 then is will be assigned priority 4.
        5. If a priority is set on a new feature as "1", then all other feature requests for that client that have
           status=A will be reordered.
        6. This methods hits DB only once for reordering multiple features.

        """
        if not self.pk:  # inserting new feature request
            if self.status == 'A':
                    max_priority = Features.objects.filter(client=self.client, status='A').aggregate(
                        Max('priority'))['priority__max']
                    if self.priority ==0:
                        pass
                    elif max_priority is not None and self.priority > max_priority:
                        self.priority = max_priority + 1
                    else:
                        Features.objects.filter(client=self.client, priority__gte=self.priority,
                                                ).exclude(priority=0).update(priority=F('priority') + 1)
            else:
                self.priority = 0
        else:  # updating feature request
            old_feature_object = Features.objects.get(pk=self.pk)
            old_priority = old_feature_object.priority
            old_status = old_feature_object.status
            self.client = old_feature_object.client  # client can not be modified
            new_priority = self.priority
            new_status = self.status
            if new_priority == old_priority and new_status == old_status:
                pass  # no reordering required
            else:
                if new_status == 'A':
                    if old_priority == 0:
                        Features.objects.filter(client=self.client, priority__gte=new_priority,
                                                ).exclude(priority=0).update(priority=F('priority') + 1)
                    elif new_priority == 0:
                        Features.objects.filter(client=self.client, priority__gte=old_priority,
                                                ).exclude(priority=0).update(priority=F('priority') - 1)
                    elif new_priority > old_priority:
                        Features.objects.filter(client=self.client, priority__gt=old_priority, priority__lte=new_priority,
                                                ).exclude(priority=0).update(priority=F('priority') - 1)
                    else:
                        Features.objects.filter(client=self.client, priority__gte=new_priority, priority__lt=old_priority,
                                                ).exclude(priority=0).update(priority=F('priority') + 1)

                    max_priority = Features.objects.filter(client=self.client, status='A').aggregate(
                        Max('priority'))['priority__max']

                    if max_priority is not None and new_priority > max_priority:
                        self.priority = max_priority + 1  # priority must be sequential
                else:
                    self.priority = 0  # only features that have status=A can be priorities
        super().save(*args, **kwargs)  # calling super to do the default action.

src/featurerequest/forms.py
from django import forms
import datetime

from .models import Features


class FeatureForm(forms.ModelForm):
    class Meta:
        model = Features
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'max_length': '100'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'client': forms.Select(attrs={'class': 'form-control'}),
            'priority': forms.NumberInput(attrs={'class': 'form-control'}),
            'target_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'product_area': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),

        }

    def clean(self):
        target_date = self.cleaned_data['target_date']
        status = self.cleaned_data['status']
        if status == 'A' and target_date < datetime.date.today():
            self.add_error('target_date', 'Active Feature Request can not have a past Target date.')
        super().clean()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=150)
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}), min_length=8)

src/featurerequest/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import LoginForm, FeatureForm
from .models import Features


@login_required
def index(request, page=1):
    """
    It displays list of feature requests. 10 records will be displayed per page in descending order of target_date.
    :param request: HttpRequest object provided by django engine.
    :param page: the page number that needs to be displayed.

    """
    latest_feature_list = Features.objects.filter().order_by('-target_date')
    paginator = Paginator(latest_feature_list, 10)

    try:
        feature_list = paginator.page(page)
    except PageNotAnInteger:
        feature_list = paginator.page(1)  # show first page if page is not PageNotAnInteger
    except EmptyPage:
        feature_list = paginator.page(paginator.num_pages)

    startPoint = 1
    endPoint = feature_list.paginator.num_pages

    if feature_list.paginator.num_pages > 10:
        if feature_list.number < 6:
            startPoint = 1
            endPoint = 10
        elif feature_list.number + 4 >= feature_list.paginator.num_pages:
            startPoint = feature_list.paginator.num_pages - 9
            endPoint = feature_list.paginator.num_pages
        else:
            startPoint = feature_list.number - 5
            endPoint = feature_list.number + 4

    pageList = range(startPoint, endPoint + 1)

    return render(request, 'featurerequest/index.html', {'feature_list': feature_list, 'pageList': pageList})


@login_required
def add_features(request):
    """
    Creates Feature Request on POST.
    Blank form will be rendered on GET.

    """
    feature_form = FeatureForm(request.POST or None)
    if request.method == 'POST':
        if feature_form.is_valid():
            feature_form.save()
            messages.success(request, 'The Feature request was successfully created!.')
            return redirect('/features/')
        else:
            messages.error(request, 'Please correct the error below.')
            return render(request, 'featurerequest/addfeatures.html', {'feature_form': feature_form})
    else:
        feature_form = FeatureForm()
        return render(request, 'featurerequest/addfeatures.html', {'feature_form': feature_form})


def userlogin(request):
    """
    Blank login form will be rendered on GET
    User will be logged in and redirected to Features page on providing valid credentials.

    """
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/features/')
    return render(request, 'featurerequest/login.html', {'login_form': form})


def userlogout(request):
    """
    User will be logged out.
    """
    logout(request)
    return redirect('/features/')

src/featurerequest/templates/featurerequest/addfeatures.html
{% extends "featurerequest/base.html"%}
{% load static %}
{% block mainContent %}

<div class="col-md-8">
    {% if feature_form.errors %}
        {% for error in feature_form.non_field_errors %}
            <div class="alert alert-danger non-field-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
<form role="form" class="form-horizontal" id="login-form" method="post" action="{% url 'featurerequest:add_features' %}"
data-bind="submit: doSomething">
    {% csrf_token %}
    {{ feature_form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>
<script type="text/javascript">
    var viewModel = {
        doSomething : function(formElement) {
            if(formElement.priority.value < 0)
            {
                alert("Priority can not be negative.");
                return false;
            }

            return true;
        }
    };
    ko.applyBindings(viewModel);
</script>
{% endblock mainContent %}

src/featurerequest/templates/featurerequest/base.html
{% load static %}
<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>serviceITnow</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static "featurerequest/css/custom.css" %}"/>
    </head>
    <body>
        <nav class="navbar navbar-light bg-faded rounded navbar-toggleable-md mb-3" style="background-color: #bebebe;">
        <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse"
                data-target="#containerNavbar" aria-controls="containerNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">serviceITnow</a>
        <div class="navbar-collapse collapse" id="containerNavbar" aria-expanded="false">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Feature Request<span class="sr-only">(current)</span></a>
                </li>
            </ul>
             <ul class="navbar-nav my-2 my-md-0">
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link">Hi {{ request.user.first_name | title }}! </span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-hidden="true" href="{% url 'featurerequest:userlogout' %}">
                                <i class="fa fa-power-off fa-lg" aria-hidden="true"></i>
                            </a>

                        </li>


                    {% else %}
                        <a class="nav-link" href="{% url 'featurerequest:userlogin' %}" >Sign in</a>
                    {% endif %}

                </li>
            </ul>
        </div>
        </nav>

        <div class="container  custom_height">
            <div class="row-fluid">
                <div class="col-md-8 col-xs-12">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="col-md-12 col-xs-12">
                    {% block mainContent %}Site Content {% endblock mainContent %}
                </div>
                <!--<div class="col-md-4 col-xs-12">-->
                    <!--<div class="sidebar section" id="sidebar">-->
                    <!--</div>-->
                <!--</div>-->
            </div>
        </div>
        <footer class="footer" style="background-color: #bebebe;">
            <div class="container py-2">
                <span class="text-muted">2018 <a href="/">serviceITnow</a></span>

            </div>
        </footer>
    </body>
</html>

src/featurerequest/templates/featurerequest/index.html
{% extends "featurerequest/base.html"%}
{% load static %}
{% block mainContent %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <ul class="pagination">
            <li class="page-item active"><a class="page-link" href="{% url 'featurerequest:add_features' %}" >Create Feature Request</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        {% for feature_obj in feature_list %}
            <div class="col-md-4 col-xs-4">
                <div class="card mb-2" id="cont-{{ feature_obj.id }}">
                    <div class="card-block" style="background-color: #eeeeee;">
                        <h4 class="card-title"><a href="#">{{ feature_obj.title }}</a></h4>
                        <h6 class="card-subtitle mb-2 text-muted">Client : {{ feature_obj.client }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Product Area : {{ feature_obj.product_area }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Status : {{ feature_obj.status }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Target Date : {{ feature_obj.target_date|date:"M d, Y" }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Priority : {{ feature_obj.priority }}</h6>
                        <p class="card-text">{{ feature_obj.description|slice:":200"|safe }}  ... </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-md-12 col-xs-12">

            <nav aria-label="page-navigation">
            <ul class="pagination">
                {% if feature_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'featurerequest:index-withpage' feature_list.previous_page_number %}" tabindex="-1">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1">Previous</a>
                    </li>
                {% endif %}

                {% for i in pageList %}
                    {% if i == feature_list.number %}
                        <li class="page-item active"><a class="page-link" href="{% url 'featurerequest:index-withpage' i %}" >{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url 'featurerequest:index-withpage' i %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if latest_edi_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'featurerequest:index-withpage' feature_list.next_page_number %}" tabindex="-1">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1">Next</a>
                    </li>
                {% endif %}
            </ul>
            </nav>


        </div>
    </div>

{% endblock mainContent %}

src/featurerequest/templates/featurerequest/login.html
{% extends "featurerequest/base.html"%}
{% load static %}
{% block mainContent %}
<div class="col-md-8">
    {% if login_form.errors %}
    {% for field in login_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in login_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<form role="form" class="form-horizontal" id="login-form" method="post" action="{% url 'featurerequest:userlogin' %}">
    {% csrf_token %}
  {{ login_form.as_p }}

    <input type="submit" value="Submit" />
</form>
</div>
{% endblock mainContent %}